version: "3"
services:
  alexa-subwatch:
    image: simplysublime/alexa-subwatch:latest
    container_name: alexa-subwatch
    volumes:
      - ./subwatch:/config
    ports:
      - 5000:5000
    restart: unless-stopped

  serveo:
    image: simplysublime/serveo:latest
    container_name: alexa-subwatch-serveo
    tty: true
    stdin_open: true
    # see https://serveo.net/ for more options
    command: autossh -M 0 -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -o StrictHostKeyChecking=no -R 443:alexa-subwatch:5000 serveo.net
